// Pacote EAP 1.2.4 — Interface por etapa.
// Metadados estáticos das 17 fases do organograma de processo. Isto é só
// texto e a referência a qual seção do dossiê cada fase lê/escreve — nenhuma
// lógica de análise mora aqui. Quando a fase 02 (ingestão de vídeo) for
// implementada de verdade, o código dela lê este mesmo array para saber
// qual tela ativar.

// tipo espelha a classificação de custo/decisão do organograma:
// "padrao" = automático no navegador, sem custo | "pago" = chamada de
// modelo | "humano" = decisão humana obrigatória.
export const FASES = [
  {
    numero: "00",
    titulo: "Fundação",
    subtitulo: "O que se decide antes do código.",
    tipo: "humano",
    entra: "A estação física e o SOP feito à mão pelo ilustrador.",
    sai: "Mapa de zonas da bancada, glossário, lista de verbos, bíblia visual, padrão de gravação.",
    gate: "O mapa cobre todo lugar onde a mão do operador vai buscar alguma coisa.",
    secaoDossie: "mapaDeZonas",
    notaSecao: "Só o mapa de zonas vira seção do dossiê. Glossário, verbos, bíblia visual e protocolo de gravação são reusados entre vídeos e ainda não têm lugar no formato — hoje ficam fora do dossiê, na futura biblioteca da estação (F16-06).",
  },
  {
    numero: "01",
    titulo: "O dossiê",
    subtitulo: "O contrato de dados entre todas as fases.",
    tipo: "padrao",
    entra: "As definições da fase 00.",
    sai: "O arquivo único que todas as fases leem e alimentam, sem nunca apagar.",
    gate: "Um dossiê fictício percorre a página inteira, é exportado, reimportado e continua íntegro.",
    secaoDossie: null,
    ehContainer: true,
  },
  {
    numero: "02",
    titulo: "Ingestão do vídeo",
    subtitulo: "Trazer o arquivo para dentro e conferir se ele serve.",
    tipo: "padrao",
    entra: "Arquivo MP4 da gravação.",
    sai: "Vídeo aprovado na triagem, com início e fim úteis marcados.",
    gate: "Resolução, duração e enquadramento batem com o mapa de zonas.",
    secaoDossie: "origemVideo",
  },
  {
    numero: "03",
    titulo: "Extração de frames",
    subtitulo: "Transformar movimento em uma pilha de imagens comparáveis.",
    tipo: "padrao",
    entra: "Vídeo aprovado.",
    sai: "~1.200 frames, miniaturas, curva de movimento geral e uma curva por zona da bancada.",
    gate: "As curvas por zona acusam atividade nos escaninhos certos.",
    secaoDossie: "frames",
  },
  {
    numero: "04",
    titulo: "Ciclos e repetições",
    subtitulo: "Onde uma montagem termina e a próxima começa.",
    tipo: "padrao",
    entra: "Frames e curvas.",
    sai: "O vídeo cortado em N montagens completas, com os ciclos sujos descartados.",
    gate: "A contagem automática bate com a contagem feita a olho.",
    secaoDossie: "ciclos",
  },
  {
    numero: "05",
    titulo: "Micro-ações",
    subtitulo: "As fronteiras naturais dentro de uma montagem.",
    tipo: "padrao",
    entra: "Ciclos recortados.",
    sai: "De 6 a 15 fatias por ciclo, cada uma com sua causa (componente novo, troca de ferramenta, pausa) e um frame-chave.",
    gate: "As fronteiras fazem sentido para um olho humano assistindo ao vídeo.",
    secaoDossie: "microAcoes",
  },
  {
    numero: "06",
    titulo: "Leitura semântica",
    subtitulo: "A primeira vez que se paga por inteligência.",
    tipo: "pago",
    entra: "Frames-chave com contexto, glossário e a zona que a mão visitou.",
    sai: "Cada fatia descrita: verbo, componente, ferramenta, mão, confiança.",
    gate: "80% das fatias vêm coerentes e nenhum nome está fora do glossário.",
    secaoDossie: "microAcoes",
    notaSecao: "A leitura enriquece as mesmas fatias da fase 05, gravando uma nova versão de microAcoes com o campo leituraSemantica em cada uma. Chama o Gemini através de uma função própria (api/leitura-semantica.js) — é a única parte do projeto que sai do navegador, porque a chave paga não pode ficar no lado do cliente. O glossário usado hoje é uma lista aberta pelo mapa de zonas, não o glossário completo do pacote 1.1.3 (ainda não construído).",
  },
  {
    numero: "07",
    titulo: "Consenso entre ciclos",
    subtitulo: "O que aconteceu em todos os ciclos é procedimento.",
    tipo: "padrao",
    entra: "As leituras de todos os ciclos.",
    sai: "O núcleo do procedimento — o que se repetiu em 80% dos ciclos — separado das variações.",
    gate: "Toda divergência entre ciclos está listada, nenhuma foi descartada em silêncio.",
    secaoDossie: "reconhecimento",
    notaSecao: "O núcleo do procedimento alimenta o relatório de reconhecimento da fase 08 — por ora as duas fases compartilham a mesma seção.",
  },
  {
    numero: "08",
    titulo: "Reconhecimento da estação",
    subtitulo: "A IA conta, mede e propõe. Você homologa uma vez.",
    tipo: "humano",
    entra: "Núcleo do procedimento.",
    sai: "Relatório com os números reais da estação, mais 2 ou 3 formas de encaixar isso em 6 quadros, cada uma com o que sacrifica.",
    decide: "Qual regra de agrupamento vale para a linha. Assinada e gravada.",
    gate: "Os números batem com a contagem manual e existe uma regra homologada.",
    secaoDossie: "reconhecimento",
  },
  {
    numero: "09",
    titulo: "Consolidação nos 6 passos",
    subtitulo: "Aplicar a regra homologada, sempre igual.",
    tipo: "padrao",
    entra: "Ações estáveis e a regra homologada.",
    sai: "Exatamente 6 passos, na ordem do vídeo, com as fusões duvidosas marcadas em amarelo.",
    gate: "São 6, nenhuma verificação sumiu e 4 deles coincidem com o SOP feito à mão.",
    secaoDossie: "passos",
  },
  {
    numero: "10",
    titulo: "A ficha de cada passo",
    subtitulo: "O documento que vai virar desenho.",
    tipo: "padrao",
    entra: "Os 6 passos.",
    sai: "Seis fichas completas: mãos, ferramenta, peças, critério de conclusão, risco, estado do produto antes e depois.",
    gate: "Nenhum campo obrigatório está vazio e cada ficha volta ao seu trecho de vídeo.",
    secaoDossie: "passos",
    notaSecao: "A ficha detalha os mesmos 6 passos da fase 09, na mesma seção — os campos extras (mãos, risco, estado do produto) entram quando o pacote 1.6 for implementado.",
  },
  {
    numero: "11",
    titulo: "Mesa de validação humana",
    subtitulo: "A barreira que não se automatiza.",
    tipo: "humano",
    entra: "Fichas + trecho de vídeo lado a lado.",
    sai: "Fichas corrigidas e assinadas, com o original preservado ao lado da correção.",
    gate: "Uma pessoa identificada aprovou os seis passos. Nenhuma imagem é gerada antes deste aceite.",
    secaoDossie: "aprovacoes",
  },
  {
    numero: "12",
    titulo: "Prompts de ilustração",
    subtitulo: "O comando exato que a IA de imagem vai receber.",
    tipo: "padrao",
    entra: "Fichas aprovadas + bíblia visual + mapa de zonas.",
    sai: "Seis prompts em camadas, com 70% do texto idêntico entre eles, e o quadro-mestre da bancada vazia.",
    gate: "Lendo só o prompt você conseguiria desenhar a cena — e nenhum pede texto dentro da imagem.",
    secaoDossie: "prompts",
  },
  {
    numero: "13",
    titulo: "Geração das imagens",
    subtitulo: "Seis quadros, mesma família visual.",
    tipo: "pago",
    entra: "Prompts, quadro-mestre, semente fixa.",
    sai: "Seis quadros gerados em cadeia — cada um referenciando o anterior — com três variações por passo.",
    gate: "A bancada é reconhecidamente a mesma nos seis e nenhum tem texto embutido.",
    secaoDossie: "imagens",
  },
  {
    numero: "14",
    titulo: "Verificação cega",
    subtitulo: "Provar que o desenho comunica o que o vídeo mostrou.",
    tipo: "pago",
    entra: "As imagens, sozinhas, sem a ficha.",
    sai: "Nota por quadro, checagem de continuidade entre eles e teste de ordem embaralhada.",
    gate: "A sequência é reconstruível só pelas imagens, sem ler nenhuma palavra.",
    secaoDossie: "imagens",
    notaSecao: "A nota e a checagem de continuidade marcam as mesmas imagens da fase 13, na mesma seção.",
  },
  {
    numero: "15",
    titulo: "Diagramação e entrega",
    subtitulo: "Os 80% visuais e os 20% escritos, no mesmo papel.",
    tipo: "padrao",
    entra: "Seis imagens aprovadas + fichas.",
    sai: "SOP em PDF e PNG: 80% imagem, 20% texto sobreposto fora da IA, com cabeçalho e versão.",
    gate: "Um operador que nunca viu a estação executa a montagem só com o SOP na mão.",
    secaoDossie: null,
  },
  {
    numero: "16",
    titulo: "Regressão, versão e o próximo vídeo",
    subtitulo: "Como evoluir sem quebrar o que já funciona.",
    tipo: "humano",
    entra: "Qualquer melhoria proposta no programa.",
    sai: "Melhoria aprovada só depois de rodar os três vídeos do conjunto-referência e não piorar nenhum indicador.",
    gate: "Duas estações completas foram aprovadas na linha e o ganho de tempo foi medido, não estimado.",
    secaoDossie: null,
  },
];
